### ISSUE TITLE
Error annotation has a bug in multi-word selection

### ISSUE THREAD

**Issue by pmarcis** [hltfbk/MT-EQuAl#4]
If I select, e.g., `computer mouse`, it turns red. When I want to now assign a label to it, I use the right mouse button click on `mouse` and this deselects `mouse`. If I now assign a label, only `computer` is marked. `mouse` is skipped as it is not selected anymore.

**Comment by pmarcis** [comment]
A workaround is to _right-click_ somewhere outside the selected phrase. However, that is not a natural usage behaviour. I guess you do not check whether left or right mouse button has been pressed. E.g., if the right mouse button has been pressed on a _RED_ coloured token, then it should not be deselected prior to saving the annotation.

**Comment by cgirardi** [comment]
This bug appears only on Microsoft Windows platform. A quick solution could be that your
mouse is not over the selected words when you right-click to activate the error typology menu, otherwise the selected word over the mouse pointer will be deselected. I'll fix it as soon as possible, but for now to display the error menu, you just have to move your mouse away from the selected words, anywhere in the screen!

**Comment by cgirardi** [comment]
Fixed!

**Comment by pmarcis** [comment]
Great! Works!
